var LAYER;
(function (LAYER) {
    LAYER[LAYER["MAIN"] = 0] = "MAIN";
    LAYER[LAYER["BATTLE"] = 1] = "BATTLE";
    LAYER[LAYER["POP"] = 2] = "POP";
})(LAYER || (LAYER = {}));
/**游戏物体类型 */
var GAMEOBJ_TYPE;
(function (GAMEOBJ_TYPE) {
    /**子弹 */
    GAMEOBJ_TYPE[GAMEOBJ_TYPE["BULLET"] = 0] = "BULLET";
    GAMEOBJ_TYPE[GAMEOBJ_TYPE["PANEL"] = 1] = "PANEL";
    GAMEOBJ_TYPE[GAMEOBJ_TYPE["STONE"] = 2] = "STONE";
})(GAMEOBJ_TYPE || (GAMEOBJ_TYPE = {}));
var AIRCRAFT_TYPE;
(function (AIRCRAFT_TYPE) {
    AIRCRAFT_TYPE[AIRCRAFT_TYPE["MASTER"] = 0] = "MASTER";
    AIRCRAFT_TYPE[AIRCRAFT_TYPE["ENEMY_SINGLE"] = 1] = "ENEMY_SINGLE";
    AIRCRAFT_TYPE[AIRCRAFT_TYPE["ENEMY_DOUBLE"] = 2] = "ENEMY_DOUBLE";
    AIRCRAFT_TYPE[AIRCRAFT_TYPE["ENEMY_STONE"] = 3] = "ENEMY_STONE";
})(AIRCRAFT_TYPE || (AIRCRAFT_TYPE = {}));
var OPERATION_TYPE;
(function (OPERATION_TYPE) {
    OPERATION_TYPE[OPERATION_TYPE["MASTER_PANEL"] = 0] = "MASTER_PANEL";
    OPERATION_TYPE[OPERATION_TYPE["ENEMY_PANEL"] = 1] = "ENEMY_PANEL";
})(OPERATION_TYPE || (OPERATION_TYPE = {}));
/**方向 */
var DIRECTION;
(function (DIRECTION) {
    DIRECTION[DIRECTION["UP"] = 0] = "UP";
    DIRECTION[DIRECTION["DOWN"] = 1] = "DOWN";
    DIRECTION[DIRECTION["RIGHT"] = 2] = "RIGHT";
    DIRECTION[DIRECTION["LEFT"] = 3] = "LEFT";
    DIRECTION[DIRECTION["UP_RIGHT"] = 4] = "UP_RIGHT";
    DIRECTION[DIRECTION["UP_LEFT"] = 5] = "UP_LEFT";
    DIRECTION[DIRECTION["DOWN_RIGHT"] = 6] = "DOWN_RIGHT";
    DIRECTION[DIRECTION["DOWN_LEFT"] = 7] = "DOWN_LEFT";
})(DIRECTION || (DIRECTION = {}));
//# sourceMappingURL=GlobeConst.js.map